config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "donations#index"
  resources :donations
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :donation

  # validates :postal_code,presence:true, format:{with:/\A[0-9]{3}-[0-9]{4}\z/i}
  # validates :prefecture,presence:true, numericality:{other_than:0}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :user
  has_one :addresses
  # only_integerで整数のみに
  # 後半で1以上1000000以下の数字にバリデーション
  # validates :price,presence:true, numericality: {only_integer:true, greater_than_or_equal_to: 1, less_than_or_equal_to: 1000000 }
end

app/models/donation_address.rb
class DonationAddress
  # 下記読み込みでFormオブジェクトが利用できるようになる
  include ActiveModel::Model
  # フォームオブジェクトに下記仮想カラムを追加
  attr_accessor :price,:user_id,:postal_code,:prefecture,:city,:house_number,:building_name

  with_options presence:true do
    # only_integerで整数のみに
    # 後半で1以上1000000以下の数字にバリデーション
    validates :price, numericality: {only_integer:true, greater_than_or_equal_to: 1, less_than_or_equal_to: 1000000 }
    validates :postal_code, format:{with:/\A[0-9]{3}-[0-9]{4}\z/}
    validates :prefecture, numericality:{other_than:1}
    # アソシエーションで自動的についていたpresenceをformオブジェクトのバリデーションでは追記
    validates :user_id
  end
  # 各DBに保存
  def save
    @donation = Donation.create(price:price,user_id:user_id)
    # ストロングパラメーターでは無いためmergeは使わない
    Address.create(postal_code:postal_code,prefecture:prefecture,city:city,house_number:house_number,building_name:building_name,donation_id:@donation.id)
  end 
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' }, { id: 2, name: '北海道' }, { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' }, { id: 5, name: '宮城県' }, { id: 6, name: '秋田県' }, 
    { id: 7, name: '山形県' }, { id: 8, name: '福島県' }, { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' }, { id: 11, name: '群馬県' }, { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' }, { id: 14, name: '東京都' }, { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' }, { id: 17, name: '富山県' }, { id: 18, name: '石川県' },
    { id: 19, name: '福井県' }, { id: 20, name: '山梨県' }, { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' }, { id: 23, name: '静岡県' }, { id: 24, name: '愛知県' }, 
    { id: 25, name: '三重県' }, { id: 26, name: '滋賀県' }, { id: 27, name: '京都府' }, 
    { id: 28, name: '大阪府' }, { id: 29, name: '兵庫県' }, { id: 30, name: '奈良県' }, 
    { id: 31, name: '和歌山県' }, { id: 32, name: '鳥取県' }, { id: 33, name: '島根県' }, 
    { id: 34, name: '岡山県' }, { id: 35, name: '広島県' }, { id: 36, name: '山口県' }, 
    { id: 37, name: '徳島県' }, { id: 38, name: '香川県' }, { id: 39, name: '愛媛県' }, 
    { id: 40, name: '高知県' }, { id: 41, name: '福岡県' }, { id: 42, name: '佐賀県' }, 
    { id: 43, name: '長崎県' }, { id: 44, name: '熊本県' }, { id: 45, name: '大分県' }, 
    { id: 46, name: '宮崎県' }, { id: 47, name: '鹿児島県' }, { id: 48, name: '沖縄県' }
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
# with_optionsを使用すると同じバリデーwy音を複数の値へ一気にかけることができる
with_options presence: true do
  # バリデーションの設定とmessageでエラーメッセージの指定
   validates :name, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: "ひらがな/カタカナ/漢字が使用できます。" }
   validates :name_reading, format: { with: /\A[ァ-ヶー]+\z/, message: "カタカナが使用できます。" }
   validates :nickname, format: { with: /\A[a-z0-9]+\z/i, message: "半角英数字が使用できます。" }
end

   has_many :donation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  # deviseへ新たに追加するメソッドをconfigure_permitted_parametersというメソッドで作ることが慣習
  def configure_permitted_parameters
    # deviseの受け取れるパラメーターの宣言に新しいパラメーターを追加するメソッド
    # 第一引数にサインインサインアップアカウント情報の更新のどれかを記載　第三引数に追加したいカラム名のキーを記述する
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:name_reading,:nickname])
  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
    # index以外のアクションを行おうとした際にログインされてなかったらログインページに遷移する設定
    before_action :authenticate_user!, except: :index
  def index
  end
  def new
    # フォームにフォームオブジェクトを指定する用
    @donation_address = DonationAddress.new
  end
  def create 
    # まずすべてのデータをDonationAddressのフォームオブジェクトに保存
    @donation_address = DonationAddress.new(donation_address_params)
    if @donation_address.valid?
      @donation_address.save
      redirect_to root_path
    else
      render :new,status: :unprocessable_entity
    end

    # @donation = Donation.create(donation_params)
    # Address.create(address_params)
    # redirect_to root_path
  end

  private
  def donation_address_params
    # フォームでフォームオブジェクトのdonation_addressを指定したためrequireにdonation_address指定
    params.require(:donation_address).permit(:price,:user_id,:postal_code,:prefecture,:city,:house_number,:building_name).merge(user_id: current_user.id)
  end

  # def donation_params
  #   # ビューでフォームにmodelを指定していないためrequireが必要ない（requireはフォームにmodelを指定するとparamsの中でmodelハッシュが作成されて入力情報が入っているため記入している）
  #   params.permit(:price).merge(user_id: current_user.id)
  # end
  # def address_params
  #   params.permit(:postal_code,:prefecture,:city,:house_number,:building_name).merge(donation_id: @donation.id)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class = 'error-message'>
          <%= message %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/donations/index.html.erb
<%if user_signed_in? %>
  <%= current_user.name %>
  <%= link_to 'ログアウト', destroy_user_session_path,data: { turbo_method: :delete } %>
<% else%>
  <%= link_to '新規登録', new_user_registration_path%>
  <%= link_to 'ログイン', new_user_session_path%>
<% end %>
<%= link_to '寄付する', new_donation_path%>

app/views/donations/new.html.erb
<%=form_with model:@donation_address,url: donations_path, local: true do |f|%>
<%= render 'error_messages' , model: @donation_address %>
  <h1>住所</h1>
  <div class="field">
    <%= f.label :postal_code, "郵便番号(ハイフン含む)"%>
    <%= f.text_field :postal_code %>
  </div>
  <div class="field">
    <%= f.label :prefecture, "都道府県"%>
    <%= f.collection_select :prefecture, Prefecture.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :city, "市区町村(任意)"%>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :house_number, "番地(任意)"%>
    <%= f.text_field :house_number %>
  </div>
  <div class="field">
    <%=f.label :building_name, "建物名(任意)"%>
    <%= f.text_field :building_name %>
  </div>
  <h1>寄付</h1>
  <div class="field">
    <%= f.label :price, "金額(1~1,000,000)"%>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit "寄付する"%>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Donnation</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>